-- PGW NSI Quest — Schéma Supabase
-- À exécuter dans Supabase > SQL Editor sur un projet neuf ou dédié.

create extension if not exists pgcrypto;

create table if not exists public.visit_sessions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  year integer not null check (year between 2026 and 2100),
  event_date date not null,
  access_code text not null check (char_length(access_code) between 3 and 20),
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists visit_sessions_access_code_upper_idx
  on public.visit_sessions (upper(access_code));

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pseudo text not null default 'Player' check (char_length(pseudo) <= 40),
  classe text check (char_length(classe) <= 30),
  role text not null default 'student' check (role in ('student','teacher')),
  visit_session_id uuid references public.visit_sessions(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  visit_session_id uuid not null references public.visit_sessions(id) on delete cascade,
  mission_key text not null,
  question_key text not null,
  answer jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint responses_one_answer unique (user_id, visit_session_id, question_key)
);

create index if not exists responses_session_idx on public.responses (visit_session_id);
create index if not exists responses_user_idx on public.responses (user_id);

create table if not exists public.progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  visit_session_id uuid not null references public.visit_sessions(id) on delete cascade,
  mission_key text not null,
  completed boolean not null default false,
  xp integer not null default 0 check (xp >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, visit_session_id, mission_key)
);

-- Création automatique d'un profil minimal à chaque compte Supabase,
-- y compris pour l'authentification anonyme des élèves.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, pseudo, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'pseudo', 'Player'), 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Fonction helper utilisée par les policies. SECURITY DEFINER évite une récursion RLS.
create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'teacher'
  );
$$;

-- L'élève rejoint une session avec un code, sans pouvoir lister les sessions.
create or replace function public.join_visit_session(
  p_code text,
  p_pseudo text,
  p_classe text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_session public.visit_sessions%rowtype;
begin
  if v_user is null then
    raise exception 'Authentification requise.';
  end if;

  if char_length(trim(coalesce(p_pseudo,''))) < 2 then
    raise exception 'Pseudo trop court.';
  end if;

  select * into v_session
  from public.visit_sessions
  where upper(access_code) = upper(trim(p_code))
    and is_active = true
  limit 1;

  if not found then
    raise exception 'Code de mission invalide ou session fermée.';
  end if;

  insert into public.profiles (id, pseudo, classe, visit_session_id)
  values (v_user, left(trim(p_pseudo),40), left(trim(p_classe),30), v_session.id)
  on conflict (id) do update set
    pseudo = excluded.pseudo,
    classe = excluded.classe,
    visit_session_id = excluded.visit_session_id;

  return jsonb_build_object(
    'id', v_session.id,
    'title', v_session.title,
    'year', v_session.year,
    'event_date', v_session.event_date
  );
end;
$$;

-- RLS -----------------------------------------------------------------------
alter table public.visit_sessions enable row level security;
alter table public.profiles enable row level security;
alter table public.responses enable row level security;
alter table public.progress enable row level security;

-- Nettoyage idempotent des policies
drop policy if exists visit_sessions_teacher_select on public.visit_sessions;
drop policy if exists visit_sessions_teacher_insert on public.visit_sessions;
drop policy if exists visit_sessions_teacher_update on public.visit_sessions;
drop policy if exists visit_sessions_teacher_delete on public.visit_sessions;
drop policy if exists profiles_self_teacher_select on public.profiles;
drop policy if exists profiles_teacher_update on public.profiles;
drop policy if exists responses_self_teacher_select on public.responses;
drop policy if exists responses_self_insert on public.responses;
drop policy if exists responses_self_update on public.responses;
drop policy if exists responses_self_teacher_delete on public.responses;
drop policy if exists progress_self_teacher_select on public.progress;
drop policy if exists progress_self_insert on public.progress;
drop policy if exists progress_self_update on public.progress;
drop policy if exists progress_self_teacher_delete on public.progress;

create policy visit_sessions_teacher_select
on public.visit_sessions for select to authenticated
using (public.is_teacher());

create policy visit_sessions_teacher_insert
on public.visit_sessions for insert to authenticated
with check (public.is_teacher());

create policy visit_sessions_teacher_update
on public.visit_sessions for update to authenticated
using (public.is_teacher()) with check (public.is_teacher());

create policy visit_sessions_teacher_delete
on public.visit_sessions for delete to authenticated
using (public.is_teacher());

create policy profiles_self_teacher_select
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_teacher());

create policy profiles_teacher_update
on public.profiles for update to authenticated
using (public.is_teacher()) with check (public.is_teacher());

create policy responses_self_teacher_select
on public.responses for select to authenticated
using (user_id = auth.uid() or public.is_teacher());

create policy responses_self_insert
on public.responses for insert to authenticated
with check (
  user_id = auth.uid()
  and visit_session_id = (select p.visit_session_id from public.profiles p where p.id = auth.uid())
);

create policy responses_self_update
on public.responses for update to authenticated
using (
  user_id = auth.uid()
  or public.is_teacher()
)
with check (
  (user_id = auth.uid() and visit_session_id = (select p.visit_session_id from public.profiles p where p.id = auth.uid()))
  or public.is_teacher()
);

create policy responses_self_teacher_delete
on public.responses for delete to authenticated
using (user_id = auth.uid() or public.is_teacher());

create policy progress_self_teacher_select
on public.progress for select to authenticated
using (user_id = auth.uid() or public.is_teacher());

create policy progress_self_insert
on public.progress for insert to authenticated
with check (
  user_id = auth.uid()
  and visit_session_id = (select p.visit_session_id from public.profiles p where p.id = auth.uid())
);

create policy progress_self_update
on public.progress for update to authenticated
using (user_id = auth.uid() or public.is_teacher())
with check (
  (user_id = auth.uid() and visit_session_id = (select p.visit_session_id from public.profiles p where p.id = auth.uid()))
  or public.is_teacher()
);

create policy progress_self_teacher_delete
on public.progress for delete to authenticated
using (user_id = auth.uid() or public.is_teacher());

-- Permissions API. Le RLS reste l'autorité finale.
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.visit_sessions to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.responses to authenticated;
grant select, insert, update, delete on public.progress to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.join_visit_session(text,text,text) to authenticated;
grant execute on function public.is_teacher() to authenticated;

-- Session initiale 2026. Vous pourrez ensuite gérer les éditions dans le cockpit.
insert into public.visit_sessions (title, year, event_date, access_code, is_active)
select 'PGW NSI 2026', 2026, date '2026-10-23', 'PGW26', true
where not exists (
  select 1 from public.visit_sessions where upper(access_code) = 'PGW26'
);
